"""update_week_start_field

Revision ID: b81e4fcded97
Revises: cb111c0c4903
Create Date: 2024-12-18 08:48:12.625251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b81e4fcded97'
down_revision: Union[str, None] = 'cb111c0c4903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chore_assignments', sa.Column('week_start', sa.Date(), nullable=False))
    op.add_column('chore_assignments', sa.Column('occurrence_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chore_assignments', 'occurrence_number')
    op.drop_column('chore_assignments', 'week_start')
    # ### end Alembic commands ###
