"""replace_points_with_frequency_per_week

Revision ID: cb111c0c4903
Revises: 31eeda375f6e
Create Date: 2024-12-17 08:06:58.677635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cb111c0c4903'
down_revision: Union[str, None] = '31eeda375f6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('frequency_per_week', sa.Integer(), nullable=True))
    op.drop_column('chores', 'points')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chores', sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chores', 'frequency_per_week')
    # ### end Alembic commands ###
